### ISSUE TITLE
Is it convenient for you to provide raw data for the experiment?

### ISSUE THREAD

**Issue by xsqiao** [xiaobaishu0097/ECCV-VN#2]
The data in README is missing `depth.hdf5` and `det_feature_60_categes.hdf5`.Is it convenient for you to provide it?

**Comment by xiaobaishu0097** [comment]
The detection feature file should be 'fasterrcnn_features_22cls.hdf5'.
BTW, we didn't use depth in our experiment.

**Comment by destination-xy** [comment]
Excuse me,How do I get the file "fasterrcnn_features_22cls.hdf5"?

**Comment by xiayule01** [comment]
> The detection feature file should be 'fasterrcnn_features_22cls.hdf5'. BTW, we didn't use depth in our experiment.

Process Process-9:
Traceback (most recent call last):
  File "/home/commpn-dir/yutao/miniconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/commpn-dir/yutao/miniconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/commpn-dir/yutao/ECCV-VN-master/runners/a3c_train.py", line 67, in a3c_train
    total_reward = run_episode(player, args, total_reward, model_options, True)
  File "/home/commpn-dir/yutao/ECCV-VN-master/runners/train_util.py", line 31, in run_episode
    player.action(model_options, training, update_test)
  File "/home/commpn-dir/yutao/ECCV-VN-master/agents/agent.py", line 151, in action
    model_input, out = self.eval_at_state(model_options)
  File "/home/commpn-dir/yutao/ECCV-VN-master/agents/navigation_agent.py", line 47, in eval_at_state
    current_detection_feature = current_detection_feature[self.targets_index, :]
IndexError: index 22 is out of bounds for axis 0 with size 22



Excuse me. How to fix this error?
